<Project>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <RestoreDisableParallel>false</RestoreDisableParallel>
        <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
        <MSBuildCopyContentTransitively>true</MSBuildCopyContentTransitively>
        <Features>$(Features);strict</Features>
        <WarningLevel>9999</WarningLevel>
        <Deterministic>false</Deterministic>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <NoWarn>$(NoWarn);IDE0008;IDE0011;IDE0022;IDE0055;IDE0065;IDE0130;IDE0160</NoWarn>
        <Company>TBC Bank</Company>
        <Copyright>&#169; TBC Bank</Copyright>
        <Authors>galkhazishvili</Authors>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <DebugType>embedded</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PackageProjectUrl>https://github.com/TBCBank/TBC.OpenBanking.Jws</PackageProjectUrl>
        <RepositoryUrl>https://github.com/TBCBank/TBC.OpenBanking.Jws</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(TF_BUILD)' == 'True' or '$(GITHUB_ACTIONS)' == 'true' ">
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <DisableImplicitAspNetCoreAnalyzers>true</DisableImplicitAspNetCoreAnalyzers>
        <DisableImplicitComponentsAnalyzers>true</DisableImplicitComponentsAnalyzers>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
    </PropertyGroup>
    <Import Project="$(MSBuildThisFileDirectory)Local.Build.props" Condition="Exists('$(MSBuildThisFileDirectory)Local.Build.props')" />
</Project>
