<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<RootNamespace>TBC.OpenBanking.Jws.Tests</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
		<NoWarn>$(NoWarn);IDE0017;IDE0300;IDE0301;IDE0305</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\TBC.OpenBanking.Jws\src\TBC.OpenBanking.Jws.csproj" />
	</ItemGroup>

</Project>
