# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'src/images/**'
      - 'README.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'images/**'
      - 'src/images/**'
      - 'README.md'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_MULTILEVEL_LOOKUP: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore --disable-parallel -p:Configuration=Release

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --no-build --verbosity normal
