# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'images/**'
      - 'src/images/**'
      - 'README.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'images/**'
      - 'src/images/**'
      - 'README.md'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_DISABLE_GUI_ERRORS: 1
      DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore
      run: dotnet restore -p:Configuration=Release

    - name: Build
      run: dotnet build -c Release --no-restore -p:SourceRevisionId=$(git rev-parse --short $GITHUB_SHA)

    # There are no tests yet.
    #- name: Test
    #  run: dotnet test -c Release --no-restore --no-build --verbosity normal
