# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: NuGet

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'src/images/**'
      - 'src/examples/**'
      - 'README.md'
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_MULTILEVEL_LOOKUP: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

    # Use vanilla NuGet.exe because dotnet nuget command has a bug: it ignores --source parameter
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: latest
        nuget-api-key-source: 'https://api.nuget.org/v3/index.json'

    - name: Restore
      run: dotnet restore --disable-parallel -p:Configuration=Release

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --no-build --verbosity normal

    - name: Push Jws
      run: nuget push "src\TBC.OpenBanking.Jws\src\bin\Release\*.nupkg" -NonInteractive -SkipDuplicate -Source "https://api.nuget.org/v3/index.json"

    - name: Push Jws.Http
      run: nuget push "src\TBC.OpenBanking.Jws.Http\src\bin\Release\*.nupkg" -NonInteractive -SkipDuplicate -Source "https://api.nuget.org/v3/index.json"
