name: NuGet

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_MULTILEVEL_LOOKUP: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup .NET 5 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400

    - name: Restore
      run: dotnet restore --disable-parallel

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Push Jws
      run: dotnet nuget push "src\TBC.OpenBanking.Jws\src\bin\Release\*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"

    - name: Push Jws.Http
      run: dotnet nuget push "src\TBC.OpenBanking.Jws.Http\src\bin\Release\*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json"
