# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: NuGet

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'src/images/**'
      - 'src/examples/**'
      - 'README.md'
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_DISABLE_GUI_ERRORS: 1
      DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore
      run: dotnet restore -p:Configuration=Release

    - name: Build
      run: |
        $revisionId = $(git rev-parse --short $env:GITHUB_SHA)
        dotnet build -c Release --no-restore "-p:SourceRevisionId=$revisionId"

    # There are no tests yet.
    #- name: Test
    #  run: dotnet test -c Release --no-restore --no-build --verbosity normal

    - name: Push Jws
      run: dotnet nuget push "src\TBC.OpenBanking.Jws\src\bin\Release\*.nupkg" -k "${{ secrets.NUGET_API_KEY }}" -s "https://api.nuget.org/v3/index.json" -n --skip-duplicate --force-english-output

    - name: Push Jws.Http
      run: dotnet nuget push "src\TBC.OpenBanking.Jws.Http\src\bin\Release\*.nupkg" -k "${{ secrets.NUGET_API_KEY }}" -s "https://api.nuget.org/v3/index.json" -n --skip-duplicate --force-english-output
