name: NuGet

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_MULTILEVEL_LOOKUP: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup .NET 5 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Use vanilla NuGet.exe because dotnet nuget command has a bug: it ignores --source parameter
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: latest
        nuget-api-key-source: 'https://api.nuget.org/v3/index.json'

    - name: Restore
      run: dotnet restore --disable-parallel -p:Configuration=Release

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Push Jws
      run: nuget push "src\TBC.OpenBanking.Jws\src\bin\Release\*.nupkg" -NonInteractive -NoSymbols -SkipDuplicate -Source "https://api.nuget.org/v3/index.json"

    - name: Push Jws.Http
      run: nuget push "src\TBC.OpenBanking.Jws.Http\src\bin\Release\*.nupkg" -NonInteractive -NoSymbols -SkipDuplicate -Source "https://api.nuget.org/v3/index.json"
